/*
 * File: app/store/Accounts.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FP.store.Accounts', {
    extend: 'Ext.data.Store',

    requires: [
        'FP.model.Account'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                name: 'Peter',
                accounts: 5
            },
            {
                name: 'Lea',
                accounts: 4
            }
        ],
        model: 'FP.model.Account',
        storeId: 'accounts'
    }
});