/*
 * File: app/controller/Master.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tattlr.controller.Master', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "container#main": {
                initialize: 'onMainInitialize'
            }
        }
    },

    onMainInitialize: function(component, eOpts) {

        /* View's Drag Set Up 
        var main = component.getDraggable(),
        me = this;

        component.element.addCls('main-inner');
        component.isOpen = false;

        main.on('drag', function(draggable, event, offsetX) {
        //me.fadeButtons(offsetX / 100);
    });

    main.on('dragstart', function(draggable, event) {
        component.element.removeCls('main-inner');
        if(!component.isOpen) {

            //me.showMenuButtons();
        }
    });

    main.on('dragend', function(draggable) {

        if(component.isOpen === false && draggable.offset.x > 50) {
            draggable.setOffset(100, 0, {
                type: 'slide',
                duration: 100
            });

            component.isOpen = true;

        } else {

            draggable.setOffset(0, 0, {
                type: 'slide',
                duration: 100
            });

            component.isOpen = false;
            //me.hideMenuButtons();

        }

        component.element.addCls('main-inner');
    });


    */
    this.checkUser();
    },

    checkUser: function() {
        /* Called on Initialize of Main Container in Master Controller */

        /*
        var currentUser = Parse.User.current();

        if (currentUser) {
        // We have current user so set headers in Rest Proxy to access Parse
        // 
        var headers = {
            "X-Parse-Application-Id": "a2pPfe7u8rb4NUO9lqFGN606n7hvDltjw3Co0m5s",
            "X-Parse-REST-API-Key": "SrvankvAXg4vRYv4hmgSJAdiIZJV1WFUVikSj95J",
            "X-Parse-Session-Token": Parse.User.current()._sessionToken,
            "Content-Type": "application/json"
        };

        Ext.getStore('Accounts_Rest').getProxy().setHeaders(headers);
        Ext.getStore('UserAccounts_Rest').getProxy().setHeaders(headers);
        Ext.getStore('Transactions').getProxy().setHeaders(headers);

        FP.app.redirectTo('accounts');

    } else {
        // show the signup or login page

        FP.app.redirectTo('start');


    }
    */
    }

});