/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FP.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "container#main": {
                initialize: 'onMainInitialize'
            }
        }
    },

    onMainInitialize: function(component, eOpts) {
        var main = component.getDraggable(),
            me = this;

        component.element.addCls('main-inner');
        component.isOpen = false;

        main.on('dragstart', function(draggable, event) {
            component.element.removeCls('main-inner');
            if(!component.isOpen) {

                me.showMenuButtons();
            }
        });

        main.on('dragend', function(draggable) {

            if(component.isOpen === false && draggable.offset.x > 50) {
                draggable.setOffset(100, 0, {
                    type: 'slide',
                    duration: 100
                });

                component.isOpen = true;

            } else {

                draggable.setOffset(0, 0, {
                    type: 'slide',
                    duration: 100
                });

                component.isOpen = false;
                me.hideMenuButtons();

            }

            component.element.addCls('main-inner');
        });
    },

    showMenuButtons: function() {
        var menu = Ext.ComponentQuery.query('#menu')[0],
            buttons = menu.query('button');

        for(var i = 0; i < buttons.length; i++) {
            buttons[i].show();
        }
    },

    hideMenuButtons: function() {
        var menu = Ext.ComponentQuery.query('#menu')[0],
            buttons = menu.query('button');

        for(var i = 0; i < buttons.length; i++) {
            buttons[i].hide();
        }
    }

});