/*
 * File: app/view/Accounts.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FP.view.Accounts', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.accounts1',

    config: {
        itemId: 'accounts',
        padding: 10,
        store: 'accounts',
        itemTpl: [
            '<div class="account">',
            '    <img src="images/user.png" class="user-image" />',
            '    <span class="account-name">{name}</span><br />',
            '    <span>Accounts: {accounts}</span>',
            '</div>'
        ]
    }

});