/*
 * File: app/view/Master.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FP.view.Master', {
    extend: 'Ext.Container',

    requires: [
        'FP.view.Accounts',
        'Ext.Toolbar'
    ],

    config: {
        layout: {
            type: 'hbox'
        },
        items: [
            {
                xtype: 'container',
                cls: 'main',
                draggable: {
                    direction: 'horizontal',
                    constraint: {
                        min: {
                            x: 0,
                            y: 0
                        },
                        max: {
                            x: 100,
                            y: 0
                        }
                    }
                },
                itemId: 'main',
                style: 'background: #fff;',
                width: '100%',
                zIndex: 1,
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'green',
                            'toolbar'
                        ],
                        docked: 'top',
                        itemId: 'toolbar',
                        title: '',
                        items: [
                            {
                                xtype: 'button',
                                cls: 'green',
                                itemId: 'menuButton',
                                style: 'color: #fff;',
                                ui: 'plain',
                                iconCls: 'menu',
                                text: ''
                            },
                            {
                                xtype: 'button',
                                ui: 'plain',
                                iconCls: 'add',
                                text: 'User'
                            }
                        ]
                    },
                    {
                        xtype: 'accounts1'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                bottom: 0,
                cls: 'menu-bg',
                docked: 'left',
                itemId: 'menu',
                left: 0,
                top: 0,
                width: 100,
                zIndex: 0,
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'menu-button',
                        height: 50,
                        hidden: true,
                        margin: '0 0 5 0',
                        showAnimation: {
                            type: 'slideIn',
                            direction: 'right'
                        },
                        width: 80,
                        iconAlign: 'top',
                        iconCls: 'bookmarks',
                        text: 'Accounts'
                    },
                    {
                        xtype: 'button',
                        cls: 'menu-button',
                        height: 50,
                        hidden: true,
                        margin: '0 0 5 0',
                        showAnimation: {
                            type: 'slideIn',
                            direction: 'left'
                        },
                        width: 80,
                        iconAlign: 'top',
                        iconCls: 'team',
                        text: 'Users'
                    },
                    {
                        xtype: 'button',
                        cls: 'menu-button',
                        height: 50,
                        hidden: true,
                        margin: '0 0 5 0',
                        showAnimation: {
                            type: 'slideIn',
                            direction: 'right'
                        },
                        width: 80,
                        iconAlign: 'top',
                        iconCls: 'reports',
                        text: 'Reports'
                    },
                    {
                        xtype: 'button',
                        cls: 'menu-button',
                        height: 50,
                        hidden: true,
                        margin: '0 0 5 0',
                        showAnimation: {
                            type: 'slideIn',
                            direction: 'left'
                        },
                        width: 80,
                        iconAlign: 'top',
                        iconCls: 'settings',
                        text: 'Settings'
                    },
                    {
                        xtype: 'button',
                        cls: 'menu-button',
                        height: 50,
                        hidden: true,
                        margin: '0 0 5 0',
                        showAnimation: {
                            type: 'slideIn',
                            direction: 'right'
                        },
                        width: 80,
                        iconAlign: 'top',
                        iconCls: 'info',
                        text: 'Help'
                    }
                ]
            }
        ]
    }

});