/*
 * File: app/view/Start.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tattlr.view.Start', {
    extend: 'Ext.Container',
    alias: 'widget.start',

    config: {
        hideAnimation: 'fadeOut',
        itemId: 'start',
        padding: 20,
        style: 'background: #fff;',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'component',
                html: '<h1>tattlr</h1>',
                style: 'font-size: 2em;'
            },
            {
                xtype: 'component',
                html: 'Log in:'
            },
            {
                xtype: 'button',
                itemId: 'facebook',
                margin: '50 0 10 0',
                ui: 'action',
                text: 'Facebook'
            },
            {
                xtype: 'button',
                itemId: 'twitter',
                ui: 'confirm',
                text: 'Twitter'
            }
        ],
        listeners: [
            {
                fn: 'onFacebookTap',
                event: 'tap',
                delegate: '#facebook'
            },
            {
                fn: 'onTwitterTap',
                event: 'tap',
                delegate: '#twitter'
            }
        ]
    },

    onFacebookTap: function(button, e, eOpts) {
        var main = Ext.getCmp('main');

        // /api/Account/ExternalLogin?provider=Facebook&response_type=token&client_id=self&redirect_uri=http%3A%2F%2Ftattlr.azurewebsites.net%2F

        var ref = window.open('http://tattlr.azurewebsites.net/api/Account/ExternalLogin?provider=Facebook&response_type=token&client_id=self&redirect_uri=http%3A%2F%2Ftattlr.azurewebsites.net%2F', '_blank', 'location=yes');

        ref.addEventListener('loadstop', function(event) {

            var url = event.url;

            if(url.indexOf('access_token=') !== -1) {
                //var hash = window.location.hash.substring(1); //Puts hash in variable, and removes the # character
                //alert (hash);

                var urlSplit = url.split('=');
                var tokenSplit = urlSplit[1].split('&');

                var token = tokenSplit[0];

                localStorage.setItem('tattlrToken', token);

                console.log(token);

                var violationForm = Ext.create('Tattlr.view.ViolationForm');


                main.setActiveItem(violationForm);

                ref.close();

            }


        });
    },

    onTwitterTap: function(button, e, eOpts) {
        var main = Ext.getCmp('main');

        // /api/Account/ExternalLogin?provider=Facebook&response_type=token&client_id=self&redirect_uri=http%3A%2F%2Ftattlr.azurewebsites.net%2F

        var ref = window.open('http://tattlr.azurewebsites.net//api/Account/ExternalLogin?provider=Twitter&response_type=token&client_id=self&redirect_uri=http%3A%2F%2Ftattlr.azurewebsites.net%2F', '_blank', 'location=yes');

        ref.addEventListener('loadstop', function(event) {

            var url = event.url;

            if(url.indexOf('access_token=') !== -1) {

                var urlSplit = url.split('=');
                var tokenSplit = urlSplit[1].split('&');

                var token = tokenSplit[0];

                localStorage.setItem('tattlrToken', token);

                console.log(token);

                var violationForm = Ext.create('Tattlr.view.ViolationForm');


                main.setActiveItem(violationForm);

                ref.close();

            }


        });
    }

});